apiVersion: v1
kind: Namespace
metadata:
  name: local
---
apiVersion: "rcube.com/v1"
kind: ConfigMapCustomResource
metadata:
  namespace: local
  name: application-toggles-config
  labels:
    application: nginx-deployment
spec:
  config:
    data:
      application-toggles-config.json: |
        {
        "startNewFlow": true
        }
    schema:
      application-toggles-config.json: |
        {
            "type": "object",
            "properties": {
                "startNewFlow": {
                    "type": "boolean"
                }
            },
            "required": [
              "startNewFlow"
            ]
          }

---

apiVersion: "rcube.com/v1"
kind: ConfigMapCustomResource
metadata:
  namespace: local
  name: projected-config
  labels:
    application: nginx-deployment
spec:
  config:
    data:
      allow-snippet-annotations: "false"
      projected-config.json: |
        {
        "aProjectedConfig": true
        }
    schema:
      projected-config.json: |
        {
            "type": "object",
            "properties": {
                "aProjectedConfig": {
                    "type": "boolean"
                }
            },
            "required": [
              "aProjectedConfig"
            ]
          }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: local
  labels:
    app: nginx
    config-map-version: "master-10"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        volumeMounts:
#          - name: application-toggles-config
#            mountPath: /etc/config
          - name: projected-config
            mountPath: /etc/config
        ports:
        - containerPort: 80
      volumes:
#        - name: application-toggles-config
#          configMap:
#            name: "application-toggles-config-master-10"
        - name: projected-config
          projected:
            sources:
              - configMap:
                  name: application-toggles-config-master-10
              - configMap:
                  name: projected-config-master-10
